/**
 * @file configure_radio.c
 * @author Yuchen Zhou (yzhou276@jh.edu)
 * @brief cgi-bin program to configure the radio tuner
 * @details this program is generated by transfer the python script to C code
 *          to configure the radio tuner and set the ADC frequency, else well
 *          set the stream enable bit in the control register to enable the 
 *          radio tuner stream
 * @date 2025-04-26
 * 
 * @copyright Copyright (c) 2025
 * 
 */

/* Include */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdint.h>

int main(void)
{
    // set the content type to HTML
    printf("Content-Type: text/html\n\n");
    // print the HTML header
    printf("<html>\n");
    printf("<head>\n");
    printf("<title>Configure Radio Tuner</title>\n");
    printf("</head>\n");
    printf("<body>\n");
    printf("<h1>Configure Radio Tuner</h1>\n");
    printf("<h2>Setting up the radio now...</h2>\n");

    char* len_str  = getenv("CONTENT_LENGTH"); // get the content length from the environment variable
    int len = len_str ? atoi(len_str) : 0; // convert the content length to an integer

    char* data = malloc(len + 1); // allocate memory for the data
    if (data == NULL) {
        printf("Failed to allocate memory for data<br>\n");
        return 1;
    }

    int adc_freq    = 0; // ADC frequency
    int tune_freq   = 0; // tune frequency
    int stream_en   = 0; // stream enable flag

    // read POST data from stdin
    if (fread(data, 1, len, stdin) != len) {
        printf("Failed to read POST data<br>\n");
        free(data);
        return 1;
    }

    data[len] = '\0'; // null-terminate the string

    //printf("POST data: %s<br>\n", data); // print the POST data for debugging
    printf("<h3>");

    // parse the POST data
    char* token = strtok(data, "&");
    while (token != NULL) {
        if (sscanf(token, "adc_freq_hz=%d", &adc_freq) == 1) {
            printf("ADC Frequency: %d<br>\n", adc_freq);
        } else if (sscanf(token, "tune_freq_hz=%d", &tune_freq) == 1) {
            printf("Tune Frequency: %d<br>\n", tune_freq);
        } else if (sscanf(token, "streaming=%d", &stream_en) == 1);
        token = strtok(NULL, "&"); // get the next token
    }
    free(data); // free the allocated memory

    if(stream_en == 1) {
        printf("Streaming enabled<br>\n");
    } else {
        printf("Streaming disabled<br>\n");
    }

    printf("</h3>");
    printf("</body>\n");
    printf("</html>\n");

    return 0;

}
